/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminPortalRouteImport } from './routes/admin-portal'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentLoginIndexRouteImport } from './routes/student-login.index'
import { Route as StudentLoginSisRouteImport } from './routes/student-login.sis'
import { Route as StudentLoginLmsRouteImport } from './routes/student-login.lms'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardLmsRouteImport } from './routes/dashboard.lms'
import { Route as CoursesJobGuaranteedRouteImport } from './routes/courses.job-guaranteed'
import { Route as CoursesGovtSponsoredRouteImport } from './routes/courses.govt-sponsored'
import { Route as CoursesCertificationRouteImport } from './routes/courses.certification'
import { Route as CoursesAcademicRouteImport } from './routes/courses.academic'
import { Route as CareersKesRouteImport } from './routes/careers.kes'
import { Route as CareersApprenticeshipAbroadRouteImport } from './routes/careers.apprenticeship-abroad'
import { Route as StudentLoginSisDashboardRouteImport } from './routes/student-login.sis.dashboard'
import { Route as EnrollCategoryCourseIdRouteImport } from './routes/enroll.$category.$courseId'
import { Route as CoursesCategoryCourseIdRouteImport } from './routes/courses.$category.$courseId'

const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalRoute = AdminPortalRouteImport.update({
  id: '/admin-portal',
  path: '/admin-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginIndexRoute = StudentLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentLoginRoute,
} as any)
const StudentLoginSisRoute = StudentLoginSisRouteImport.update({
  id: '/sis',
  path: '/sis',
  getParentRoute: () => StudentLoginRoute,
} as any)
const StudentLoginLmsRoute = StudentLoginLmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => StudentLoginRoute,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLmsRoute = DashboardLmsRouteImport.update({
  id: '/dashboard/lms',
  path: '/dashboard/lms',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesJobGuaranteedRoute = CoursesJobGuaranteedRouteImport.update({
  id: '/courses/job-guaranteed',
  path: '/courses/job-guaranteed',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesGovtSponsoredRoute = CoursesGovtSponsoredRouteImport.update({
  id: '/courses/govt-sponsored',
  path: '/courses/govt-sponsored',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCertificationRoute = CoursesCertificationRouteImport.update({
  id: '/courses/certification',
  path: '/courses/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesAcademicRoute = CoursesAcademicRouteImport.update({
  id: '/courses/academic',
  path: '/courses/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersKesRoute = CareersKesRouteImport.update({
  id: '/careers/kes',
  path: '/careers/kes',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersApprenticeshipAbroadRoute =
  CareersApprenticeshipAbroadRouteImport.update({
    id: '/careers/apprenticeship-abroad',
    path: '/careers/apprenticeship-abroad',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentLoginSisDashboardRoute =
  StudentLoginSisDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => StudentLoginSisRoute,
  } as any)
const EnrollCategoryCourseIdRoute = EnrollCategoryCourseIdRouteImport.update({
  id: '/enroll/$category/$courseId',
  path: '/enroll/$category/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCategoryCourseIdRoute = CoursesCategoryCourseIdRouteImport.update({
  id: '/courses/$category/$courseId',
  path: '/courses/$category/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-portal': typeof AdminPortalRoute
  '/contact': typeof ContactRoute
  '/student-login': typeof StudentLoginRouteWithChildren
  '/careers/apprenticeship-abroad': typeof CareersApprenticeshipAbroadRoute
  '/careers/kes': typeof CareersKesRoute
  '/courses/academic': typeof CoursesAcademicRoute
  '/courses/certification': typeof CoursesCertificationRoute
  '/courses/govt-sponsored': typeof CoursesGovtSponsoredRoute
  '/courses/job-guaranteed': typeof CoursesJobGuaranteedRoute
  '/dashboard/lms': typeof DashboardLmsRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/student-login/lms': typeof StudentLoginLmsRoute
  '/student-login/sis': typeof StudentLoginSisRouteWithChildren
  '/student-login/': typeof StudentLoginIndexRoute
  '/courses/$category/$courseId': typeof CoursesCategoryCourseIdRoute
  '/enroll/$category/$courseId': typeof EnrollCategoryCourseIdRoute
  '/student-login/sis/dashboard': typeof StudentLoginSisDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-portal': typeof AdminPortalRoute
  '/contact': typeof ContactRoute
  '/careers/apprenticeship-abroad': typeof CareersApprenticeshipAbroadRoute
  '/careers/kes': typeof CareersKesRoute
  '/courses/academic': typeof CoursesAcademicRoute
  '/courses/certification': typeof CoursesCertificationRoute
  '/courses/govt-sponsored': typeof CoursesGovtSponsoredRoute
  '/courses/job-guaranteed': typeof CoursesJobGuaranteedRoute
  '/dashboard/lms': typeof DashboardLmsRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/student-login/lms': typeof StudentLoginLmsRoute
  '/student-login/sis': typeof StudentLoginSisRouteWithChildren
  '/student-login': typeof StudentLoginIndexRoute
  '/courses/$category/$courseId': typeof CoursesCategoryCourseIdRoute
  '/enroll/$category/$courseId': typeof EnrollCategoryCourseIdRoute
  '/student-login/sis/dashboard': typeof StudentLoginSisDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-portal': typeof AdminPortalRoute
  '/contact': typeof ContactRoute
  '/student-login': typeof StudentLoginRouteWithChildren
  '/careers/apprenticeship-abroad': typeof CareersApprenticeshipAbroadRoute
  '/careers/kes': typeof CareersKesRoute
  '/courses/academic': typeof CoursesAcademicRoute
  '/courses/certification': typeof CoursesCertificationRoute
  '/courses/govt-sponsored': typeof CoursesGovtSponsoredRoute
  '/courses/job-guaranteed': typeof CoursesJobGuaranteedRoute
  '/dashboard/lms': typeof DashboardLmsRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/student-login/lms': typeof StudentLoginLmsRoute
  '/student-login/sis': typeof StudentLoginSisRouteWithChildren
  '/student-login/': typeof StudentLoginIndexRoute
  '/courses/$category/$courseId': typeof CoursesCategoryCourseIdRoute
  '/enroll/$category/$courseId': typeof EnrollCategoryCourseIdRoute
  '/student-login/sis/dashboard': typeof StudentLoginSisDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-portal'
    | '/contact'
    | '/student-login'
    | '/careers/apprenticeship-abroad'
    | '/careers/kes'
    | '/courses/academic'
    | '/courses/certification'
    | '/courses/govt-sponsored'
    | '/courses/job-guaranteed'
    | '/dashboard/lms'
    | '/dashboard/student'
    | '/student-login/lms'
    | '/student-login/sis'
    | '/student-login/'
    | '/courses/$category/$courseId'
    | '/enroll/$category/$courseId'
    | '/student-login/sis/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-portal'
    | '/contact'
    | '/careers/apprenticeship-abroad'
    | '/careers/kes'
    | '/courses/academic'
    | '/courses/certification'
    | '/courses/govt-sponsored'
    | '/courses/job-guaranteed'
    | '/dashboard/lms'
    | '/dashboard/student'
    | '/student-login/lms'
    | '/student-login/sis'
    | '/student-login'
    | '/courses/$category/$courseId'
    | '/enroll/$category/$courseId'
    | '/student-login/sis/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin-portal'
    | '/contact'
    | '/student-login'
    | '/careers/apprenticeship-abroad'
    | '/careers/kes'
    | '/courses/academic'
    | '/courses/certification'
    | '/courses/govt-sponsored'
    | '/courses/job-guaranteed'
    | '/dashboard/lms'
    | '/dashboard/student'
    | '/student-login/lms'
    | '/student-login/sis'
    | '/student-login/'
    | '/courses/$category/$courseId'
    | '/enroll/$category/$courseId'
    | '/student-login/sis/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminPortalRoute: typeof AdminPortalRoute
  ContactRoute: typeof ContactRoute
  StudentLoginRoute: typeof StudentLoginRouteWithChildren
  CareersApprenticeshipAbroadRoute: typeof CareersApprenticeshipAbroadRoute
  CareersKesRoute: typeof CareersKesRoute
  CoursesAcademicRoute: typeof CoursesAcademicRoute
  CoursesCertificationRoute: typeof CoursesCertificationRoute
  CoursesGovtSponsoredRoute: typeof CoursesGovtSponsoredRoute
  CoursesJobGuaranteedRoute: typeof CoursesJobGuaranteedRoute
  DashboardLmsRoute: typeof DashboardLmsRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  CoursesCategoryCourseIdRoute: typeof CoursesCategoryCourseIdRoute
  EnrollCategoryCourseIdRoute: typeof EnrollCategoryCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal': {
      id: '/admin-portal'
      path: '/admin-portal'
      fullPath: '/admin-portal'
      preLoaderRoute: typeof AdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-login/': {
      id: '/student-login/'
      path: '/'
      fullPath: '/student-login/'
      preLoaderRoute: typeof StudentLoginIndexRouteImport
      parentRoute: typeof StudentLoginRoute
    }
    '/student-login/sis': {
      id: '/student-login/sis'
      path: '/sis'
      fullPath: '/student-login/sis'
      preLoaderRoute: typeof StudentLoginSisRouteImport
      parentRoute: typeof StudentLoginRoute
    }
    '/student-login/lms': {
      id: '/student-login/lms'
      path: '/lms'
      fullPath: '/student-login/lms'
      preLoaderRoute: typeof StudentLoginLmsRouteImport
      parentRoute: typeof StudentLoginRoute
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/lms': {
      id: '/dashboard/lms'
      path: '/dashboard/lms'
      fullPath: '/dashboard/lms'
      preLoaderRoute: typeof DashboardLmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/job-guaranteed': {
      id: '/courses/job-guaranteed'
      path: '/courses/job-guaranteed'
      fullPath: '/courses/job-guaranteed'
      preLoaderRoute: typeof CoursesJobGuaranteedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/govt-sponsored': {
      id: '/courses/govt-sponsored'
      path: '/courses/govt-sponsored'
      fullPath: '/courses/govt-sponsored'
      preLoaderRoute: typeof CoursesGovtSponsoredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/certification': {
      id: '/courses/certification'
      path: '/courses/certification'
      fullPath: '/courses/certification'
      preLoaderRoute: typeof CoursesCertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/academic': {
      id: '/courses/academic'
      path: '/courses/academic'
      fullPath: '/courses/academic'
      preLoaderRoute: typeof CoursesAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/kes': {
      id: '/careers/kes'
      path: '/careers/kes'
      fullPath: '/careers/kes'
      preLoaderRoute: typeof CareersKesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/apprenticeship-abroad': {
      id: '/careers/apprenticeship-abroad'
      path: '/careers/apprenticeship-abroad'
      fullPath: '/careers/apprenticeship-abroad'
      preLoaderRoute: typeof CareersApprenticeshipAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-login/sis/dashboard': {
      id: '/student-login/sis/dashboard'
      path: '/dashboard'
      fullPath: '/student-login/sis/dashboard'
      preLoaderRoute: typeof StudentLoginSisDashboardRouteImport
      parentRoute: typeof StudentLoginSisRoute
    }
    '/enroll/$category/$courseId': {
      id: '/enroll/$category/$courseId'
      path: '/enroll/$category/$courseId'
      fullPath: '/enroll/$category/$courseId'
      preLoaderRoute: typeof EnrollCategoryCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$category/$courseId': {
      id: '/courses/$category/$courseId'
      path: '/courses/$category/$courseId'
      fullPath: '/courses/$category/$courseId'
      preLoaderRoute: typeof CoursesCategoryCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentLoginSisRouteChildren {
  StudentLoginSisDashboardRoute: typeof StudentLoginSisDashboardRoute
}

const StudentLoginSisRouteChildren: StudentLoginSisRouteChildren = {
  StudentLoginSisDashboardRoute: StudentLoginSisDashboardRoute,
}

const StudentLoginSisRouteWithChildren = StudentLoginSisRoute._addFileChildren(
  StudentLoginSisRouteChildren,
)

interface StudentLoginRouteChildren {
  StudentLoginLmsRoute: typeof StudentLoginLmsRoute
  StudentLoginSisRoute: typeof StudentLoginSisRouteWithChildren
  StudentLoginIndexRoute: typeof StudentLoginIndexRoute
}

const StudentLoginRouteChildren: StudentLoginRouteChildren = {
  StudentLoginLmsRoute: StudentLoginLmsRoute,
  StudentLoginSisRoute: StudentLoginSisRouteWithChildren,
  StudentLoginIndexRoute: StudentLoginIndexRoute,
}

const StudentLoginRouteWithChildren = StudentLoginRoute._addFileChildren(
  StudentLoginRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminPortalRoute: AdminPortalRoute,
  ContactRoute: ContactRoute,
  StudentLoginRoute: StudentLoginRouteWithChildren,
  CareersApprenticeshipAbroadRoute: CareersApprenticeshipAbroadRoute,
  CareersKesRoute: CareersKesRoute,
  CoursesAcademicRoute: CoursesAcademicRoute,
  CoursesCertificationRoute: CoursesCertificationRoute,
  CoursesGovtSponsoredRoute: CoursesGovtSponsoredRoute,
  CoursesJobGuaranteedRoute: CoursesJobGuaranteedRoute,
  DashboardLmsRoute: DashboardLmsRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  CoursesCategoryCourseIdRoute: CoursesCategoryCourseIdRoute,
  EnrollCategoryCourseIdRoute: EnrollCategoryCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
